16 lesson
Sergo8707/tutuapp pull request #2
Opened 2017-02-02 23:02 UTC by Sergo8707

2017-02-03 22:11 UTC, psylone requested changes

2017-02-03 22:11 UTC, psylone commented on app/models/carriage.rb
> +    0
Лучше вызывать здесь исключение (так обычно в Ruby реализуют абстрактные методы). Можно также посмотреть на этот gem: https://github.com/openSUSE/abstract_method

2017-02-03 22:11 UTC, psylone commented on app/models/carriage.rb
> +  validates :number, uniqueness: { scope: :train_id }, if: :train?
В Rails 5 объект по ассоциации `belongs_to` должен обязательно существовать. Значит в данном случае поезд у вагона обязательно будет.

2017-02-03 22:11 UTC, psylone commented on app/models/carriage.rb
> +  scope :ordered, -> (order) { order(number: order ? 'asc' : 'desc') }
Можно так: `scope :ordered, -> (order = nil) { order(number: order || :desc) }`.

2017-02-03 22:11 UTC, psylone commented on app/controllers/carriages_controller.rb
> +    params.require(type.underscore.to_sym).permit(:number, :type, :train_id, :total_seats, :top_seats, :bottom_seats,
Упустил, где в форме передаётся `:total_seats`?

2017-02-03 22:11 UTC, psylone commented on app/models/cupe_carriage.rb
> +    self.total_seats = self.top_seats + self.bottom_seats
Мы как-то сохраняем значение `total_seats` в базе данных? Как оно синхронизируется с количеством мест?

2017-02-03 22:11 UTC, psylone commented on app/models/cupe_carriage.rb
> +    self.total_seats = self.top_seats + self.bottom_seats
Предлагается общее решение:

```ruby
def self.total_seats
  self.pluck(*SEATS_TYPES).flatten.sum
end

train.carriages.total_seats
```

2017-02-03 22:11 UTC, psylone commented on app/views/trains/show.html.erb
> +          <% @train.carriages.ordered(@train.carriage_order).each do |carriage| %>
Можно вынести рендеринг коллекции в паршиал.

2017-02-03 22:11 UTC, psylone commented on db/schema.rb
> +    t.boolean  "carriage_order"
Стоит по дефолту задать значение `false`.

2017-02-03 22:11 UTC, psylone commented on app/models/train.rb
> +    raise 'Неверно указан тип вагона' unless Carriage::TYPES.include?(carriage_type)
Эту проверку можно не делать, если нет нужного типа, вернётся пустой релейшен и у него метод `sum` вернёт `0`.

2017-02-03 22:11 UTC, psylone commented on app/models/train.rb
> +    raise 'Неверно указан тип сидений' unless carriage_type.constantize::SEATS_TYPES.include?(seats_type)
От этой проверки я бы также воздержался, поскольку мы обязаны знать как использовать тот или иной метод нашего API класса. То есть, так и так будет ошибка если укажем неправильный тип посадочных мест, нет необходимости дополнительно эту ошибку как-то выбрасывать.

2017-02-05 21:47 UTC, Sergo8707 commented on app/models/cupe_carriage.rb
> +    self.total_seats = self.top_seats + self.bottom_seats
что-то я не совсем понял как его применить?

2017-02-06 20:25 UTC, psylone commented on app/models/cupe_carriage.rb
> +    self.total_seats = self.top_seats + self.bottom_seats
О, прошу прощения, пропустил момент с тем что поезд включает вагоны разных типов. Тогда мы можем выбрать все вагоны поезда, затем с помощью `pluck` выбрать значения количества мест (всех типов) и сложить их.

Что касается количества мест для одного вагона, здесь да должен быть метод экземпляра:

```ruby
def total_seats
  self.attributs.slice(*SEATS_TYPES).values.sum
end
```

Тогда этот метод также можно использовать для подсчёта общего количества мест в поезде: `train.carriages.map(&:total_seats).sum`.

2017-02-06 21:20 UTC, psylone commented on app/models/carriage.rb
> +      self.number = nil;
Не нужна `;`.

2017-02-06 21:20 UTC, psylone commented on app/models/carriage.rb
> +    !train.nil?
Чем предыдущий вариант не устроил?

2017-02-06 21:20 UTC, psylone commented on Gemfile
> +gem  'abstract_method'
Используешь в итоге абстрактный метод?

2017-02-06 21:20 UTC, psylone commented on app/models/carriage.rb
> +      superclass.model_name
Я бы всё же не стал так делать потому что мы ожидаем получить объект `ActiveModel::Name`, который хранит состояние в отношении текущего класса, а получается что состояние берётся от класса родителя.

Кроме того, можешь пожалуйста пояснить смысл этого переопределения?

2017-02-06 21:20 UTC, psylone commented on app/views/trains/show.html.erb
> -<p>
Как теперь выводится информация о количестве мест?

2017-02-07 19:50 UTC, Sergo8707 commented on app/models/carriage.rb
> +      superclass.model_name
Для меня это метод как и многое в Rails магия. Списал как и все :-) И как записаться на индивидуальный урок? Чтобы вы меня немного просветили. А то неделю никак один урок не могу сдать.

2017-02-07 19:50 UTC, Sergo8707 commented on app/models/carriage.rb
> +      self.number = nil;
Убрал

2017-02-07 19:50 UTC, Sergo8707 commented on Gemfile
> +gem  'abstract_method'
Использовал. Вернее пытался. Но так меня и не озарило зачем он нужен.

2017-02-07 19:51 UTC, Sergo8707 commented on app/views/trains/show.html.erb
> -<p>
Если для конкретного типа вагона и места то через метод `count_seats_by_type` например `<%= @train.count_seats_by_type(CupeCarriage, :bottom_seats) %>`  а в общем рендерит через вьюху carriage

2017-02-08 21:08 UTC, psylone commented on app/models/carriage.rb
> +      superclass.model_name
> Как я понимаю этот метод вызывается каждый раз когда наследуется какой - то дочерний класс. 

Это верно.

> Первый раз , когда метод будет выполняется, base.model_name будет возвращать ложь. И для этого вызывается super. Дальше superclass возвращает родительский класс в цепочке наследования а метод model_name использован для получения всех видов присвоения имен.

Метод `self.inherited` вызывается один раз для каждого дочернего класса в момент когда интерпретатор видит определение `class B < A`.

В качестве аргумента передаётся этот дочерний класс. Когда ты внутри метода `self.inherited` вызываешь `super` ты вызываешь этот же метод `self.inherited` у родительского класса.

Далее ты определяешь метод только для объекта дочернего класса. В нашем примере это класс `B`. В результате этого определения при вызове метода `model_name` будет возвращаться объект `ActiveModel::Name` с информацией не для класса `B`, а для класса `A`.

2017-02-08 21:09 UTC, psylone commented on app/models/carriage.rb
> +      superclass.model_name
> И как записаться на индивидуальный урок? Чтобы вы меня немного просветили. А то неделю никак один урок не могу сдать. Я так ни в какие сроки не уложусь.

Напиши пожалуйста мне в личном сообщении на форуме темы которые ты хочешь разобрать и мы договоримся о дате и времени занятия.

2017-02-08 21:09 UTC, psylone approved these changes

2017-02-08 21:46 UTC, merged